"""
schemas/chat.py — Pydantic models for the /v1/chat endpoint.

Skill pattern: Type everything, validate early with Field constraints.
"""

from pydantic import BaseModel, Field
from typing import Optional, List


class ChatRequest(BaseModel):
    session_id: str = Field(
        ...,
        min_length=1,
        max_length=100,
        description="Unique session identifier — generated by the client",
        examples=["sess-abc123"],
    )
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="User message in Urdu or English",
        examples=["مجھے کراچی میں ایک پلمبر چاہیے"],
    )
    language: str = Field(
        default="ur",
        pattern="^(ur|en)$",
        description="Response language: 'ur' for Urdu, 'en' for English",
    )
    user_phone: str | None = Field(
        default=None,
        max_length=20,
        description="Optional registered phone number to identify the user",
        examples=["03001234567"],
    )


class ProviderResult(BaseModel):
    """A single negotiated provider returned by the Munasib agent."""
    rank: int = Field(..., ge=1, le=3)
    name: str
    address: str
    rating: float = Field(..., ge=0.0, le=5.0)
    distance_km: float = Field(..., ge=0.0)
    munasib_price_estimate: str = Field(
        ..., description="e.g. 'PKR 800–1200'"
    )
    justification_ur: str = Field(
        ..., description="Urdu justification for the price estimate"
    )
    justification_en: str = Field(
        ..., description="English justification for the price estimate"
    )


class TraceStep(BaseModel):
    """A single agent thought — streamed to the frontend for visual impact."""
    name: str = Field(..., description="Name of the agent (e.g., TriageAgent)")
    status: str = Field(default="done")
    timestamp: str = Field(...)
    input: str = Field(default="")
    thinking: str = Field(default="")
    output: str = Field(default="")


class ChatResponse(BaseModel):
    session_id: str
    reply: str = Field(..., description="Main bilingual message to user")
    providers: Optional[List[ProviderResult]] = Field(
        default=None,
        description="Top 3 ranked providers (present after negotiation)",
    )
    trace_steps: Optional[List[TraceStep]] = Field(
        default=None,
        description="Agent reasoning steps for the frontend trace view",
    )
