"""
schemas/trace.py — Pydantic models for agent trace logs.

Trace logs are stored in-memory (Phase 1) and returned via /v1/trace/{session_id}.
In Phase 2 these will be persisted to Supabase PostgreSQL.
"""

from pydantic import BaseModel, Field
from typing import Optional


class TraceLog(BaseModel):
    """A single agent decision log entry."""
    timestamp: str = Field(
        ...,
        description="ISO-8601 timestamp of when this step occurred",
        examples=["2026-05-15T20:00:00Z"],
    )
    agent_name: str = Field(
        ...,
        description="Name of the agent that produced this log",
        examples=["TriageAgent", "DiscoveryAgent", "NegotiationAgent", "BookingAgent"],
    )
    input: str = Field(
        ...,
        description="The prompt or data received by the agent",
    )
    output: str = Field(
        ...,
        description="The response or tool call generated by the agent",
    )
    reasoning: Optional[str] = Field(
        default=None,
        description="Internal thought process extracted from the LLM (if supported)",
    )


class TraceResponse(BaseModel):
    """Full trace log for a session — returned by GET /v1/trace/{session_id}."""
    session_id: str
    total_steps: int
    logs: list[TraceLog]
